# 主程序执行代码

In [1]:
import warmUpExercise as warm
import numpy as np

### 热身练习
    读取warmUpExercise文件，执行warmUpExercise函数

In [3]:
print('Running warmUpExercise ... \n')
print('5x5 Identity Matrix: ')
warm.generateMatrix(3)
print('Program paused. Press enter to continue.\n')

Running warmUpExercise ... 

5x5 Identity Matrix: 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Program paused. Press enter to continue.

